# Generated by Django 5.1.4 on 2025-03-12 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="usuario",
        ),
        migrations.AddField(
            model_name="cliente",
            name="cliente",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
