# Generated by Django 5.1.4 on 2025-04-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cliente_cliente'),
        ('loja', '0008_pagamento_aprovado'),
    ]

    operations = [
    ]
